Repository devsoc-unsw/notangles, pull requests merged in 2025-05, with the labels that each got.

#983 chore(deps): Bump minor version of all client and server deps
  .github/workflows/docker-ci.yml
  auto_server/Dockerfile
  client/Dockerfile
  client/package.json
  client/pnpm-lock.yaml
  client/pnpm-workspace.yaml
  server/Dockerfile
  server/package.json
  server/pnpm-lock.yaml
  server/pnpm-workspace.yaml
Labels: 📦 dependencies 🚛

#977 Add new colour theme feature
  client/package.json
  client/pnpm-lock.yaml
  client/src/App.tsx
  client/src/components/controls/ColorOptions.tsx
  client/src/components/controls/ColorPicker.tsx
  client/src/components/controls/CourseSelect.tsx
  client/src/components/controls/CustomEvent.tsx
  client/src/components/sidebar/ColorThemeOptions.tsx
  client/src/components/sidebar/ColorThemePreview.tsx
  client/src/components/sidebar/Settings.tsx
  client/src/components/timetable/DroppedEvent.tsx
  client/src/components/timetableTabs/TimetableTabs.tsx
  client/src/constants/defaults.ts
  client/src/constants/theme.ts
  client/src/constants/timetable.ts
  client/src/context/AppContext.tsx
  client/src/hooks/useColorDecoder.ts
  client/src/styles/DroppedCardStyles.tsx
  client/src/utils/Drag.ts
  client/src/utils/oklchCovert.ts
Labels: 🍀 feature 🪴, 🐤 good first issue 🐣

#989 Fix course ID not being populated in the database
  server/src/user/user.service.ts
Labels: 🐞 bug 🐛

#928 Update setup docs
  .github/pull_request_template.md
  README.md
  client/README.md
  client/public/privacy.html
  client/team.json
  docs/onboarding.md
  docs/typescript.md
  server/README.md
Labels: 📃 setup 🧱
