Repository devsoc-unsw/notangles, pull requests merged in 2025-02, with the labels that each got.

#932 Update sponsor list and year
  client/src/assets/sponsors/arista_black.png
  client/src/assets/sponsors/arista_white.png
  client/src/assets/sponsors/macquarie_logo_black.svg
  client/src/assets/sponsors/macquarie_logo_white.svg
  client/src/assets/sponsors/safetyculture_black.png
  client/src/assets/sponsors/safetyculture_white.png
  client/src/assets/sponsors/thetradedesk_black.png
  client/src/assets/sponsors/thetradedesk_white.png
  client/src/assets/sponsors/tiktok_logo_black.svg
  client/src/assets/sponsors/tiktok_logo_white.svg
  client/src/components/Sponsors.tsx
  client/src/components/footer/FooterLinks.tsx
  client/src/components/landingPage/Footer.tsx
  client/src/components/landingPage/SponsorsSection.tsx
  client/src/components/sidebar/About.tsx
  client/team.json
Labels: dev

#933 Add promotional card on main page for subcom recruitment
  client/src/App.tsx
  client/src/components/SubcomPromotion.tsx
Labels: feature

#934 Fix year in subcom promotional popup
  LICENSE
  README.md
  client/src/components/SubcomPromotion.tsx
Labels: bug
