Repository devsoc-unsw/notangles, pull requests merged in 2025-03, with the labels that each got.

#941 chore(deps): bump to node v22 in CI
  .github/workflows/ci.yml
Labels: github_actions, deps: javascript

#944 fix(deps): remove package-lock.json
  server/package-lock.json
Labels: bug, deps: javascript

#946 chore(deps): Pin all deps and bump Prisma
  client/package.json
  client/pnpm-lock.yaml
  server/package.json
  server/pnpm-lock.yaml
  server/prisma/migrations/20250322064905_upgrade_to_v6/migration.sql
  server/prisma/migrations/migration_lock.toml
Labels: dependencies, deps: javascript

#935 Refactoring subcommittee promotional banner
  client/src/components/SubcomPromotion.tsx
Labels: feature
